# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
# pull_request:
#   branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Google Cloud Project Name (bold-ally-309219, holaachat, etc.)'
        required: true
        default: 'remo-conference'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        id: test-script
        run: echo Done!

      # Test Bash
      - name: Test ternary op
        id: gcp-cleanup-versions
        shell: bash
        run: |
          [[ github.event_name == 'workflow_dispatch' ]] && env_name=workflow_dispatch_input || env_name=other_input
          echo "github.event_name: $github.event_name";
          echo "test: $env_name";

      # yeah, expose the key! (We'll dump this key later and move to secrets)
      - name: Setup gcloud environment
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Cleanup GCP stale versions
        id: gcp-cleanup-versions
        shell: bash
        run: ./.github/workflows/scripts/gcp-cleanup-versions.sh bold-ally-309219

      - name: Deploy to GCP
        id: gcp-deploy
        run: gcloud app deploy
